Feature/add date to database
eharley19/filing13F_searcher pull request #10
Opened 2021-03-15 05:37 UTC by rosealti

Extract date from xml

2021-03-17 23:51 UTC, datdo requested changes

2021-03-17 23:51 UTC, datdo commented on parser/crawler_current_events.py
> +    """function docstring"""
better doc string

2021-03-17 23:51 UTC, datdo commented on parser/database_connection.py
> +def create_and_insert_to_database(db):
what is the purpose of this?

2021-03-17 23:51 UTC, datdo commented on parser/main.py
>  from primary_doc_xml import grab_primary_doc_root
typically people use get instead of grab

2021-03-17 23:51 UTC, datdo commented on parser/requirements.txt
> +os
you don't need to put os. Its builtin

2021-03-18 00:53 UTC, rosealti commented on parser/requirements.txt
> +os
This is old. See refactor/change_names.

2021-03-18 03:11 UTC, datdo requested changes

2021-03-18 03:11 UTC, datdo commented on parser/primary_doc_xml.py
> +    """function docstring"""
docstring

2021-03-18 03:20 UTC, datdo approved these changes

2021-03-18 03:22 UTC, merged