Renamed fields in FlaskSqlAlchemyTestConfiguration in test_filters.py.
eharley19/filing13F_searcher pull request #160
Opened 2021-10-18 07:11 UTC by rosealti

2021-10-19 03:07 UTC, datdo requested changes

2021-10-19 03:07 UTC, datdo commented on python/tests/api/routes/test_filters.py
> +        self.edgar_filing1_row2 = EdgarFiling(accession_no=ACCESSION_NO_TABLE1_ROW2,
personally, I like ACCESSION_NO_2 better

2021-10-19 03:07 UTC, datdo commented on python/tests/api/routes/test_filters.py
> +        self.data_13f1_row1 = [Data13f(equity_holdings_id="67896567",
I don't understand why this change was made. Is this what you mean?:

```python
        self.data_13f_table1_row1 = Data13f(...
        self.data_13f_table1_row2 = Data13f(...
        self.data_13f_table1 = [self.data_13f_table1_row1, self.data_13f_table1_row2 ]
       ...
       send_data_to_db(self.company1, self.edgar_filing1_row1, self.data_13f_table1)
```

2021-10-20 23:03 UTC, rosealti commented on python/tests/api/routes/test_filters.py
> +        self.edgar_filing1_row2 = EdgarFiling(accession_no=ACCESSION_NO_TABLE1_ROW2,
Done

2021-10-21 00:46 UTC, datdo requested changes

2021-10-21 00:46 UTC, datdo commented on python/tests/api/routes/test_filters.py
> +        send_data_to_db(self.company_cool, self.edgar_filing_cool, self.data_13f_cool)
don't use send_data_to_db

2021-10-21 01:21 UTC, datdo requested changes

2021-10-21 01:21 UTC, datdo commented on python/tests/api/routes/test_filters.py
> +        db.session.merge(self.company_cool)
why merge instead of add?

2021-10-21 01:24 UTC, datdo approved these changes

2021-10-21 01:34 UTC, merged