Adds preliminary routes to backend api
eharley19/filing13F_searcher pull request #30
Opened 2021-04-14 04:51 UTC by eharley19

This PR adds preliminary routes to backend api.

2021-04-15 00:24 UTC, datdo requested changes

2021-04-15 00:24 UTC, datdo commented on web_backend/api.py
> +@app.route('/')
remove if not being used.

2021-04-15 00:24 UTC, datdo commented on web_backend/api.py
> +from flask import Flask, jsonify
you should move these methods into separate blueprints for ease of maintenance.

2021-04-15 00:24 UTC, datdo commented on web_backend/api.py
> +@app.route('/company/<company_id>')
don't start the route with a backslash when you move to blueprint

2021-04-15 00:24 UTC, datdo commented on web_backend/api.py
> +    primary_doc = PrimaryDoc.query.filter(PrimaryDoc.company_name.like(f"{company_id}%"))
company_id is not name. It is the CIK.

2021-04-15 00:24 UTC, datdo commented on web_backend/api.py
> +def get_company(company_id):
what if the company_id (the cik) does not exist in the database?

2021-04-15 00:24 UTC, datdo commented on web_backend/database.py
> +Base.query = db_session.query_property()
what's the point of this line?

2021-04-15 00:24 UTC, datdo commented on web_backend/database.py
> +    Base.metadata.create_all(bind=engine)
add newline at end of file.

2021-04-21 00:45 UTC, TheNorthEestern commented on web_backend/database.py
> +Base.query = db_session.query_property()
https://stackoverflow.com/a/42309468

2021-04-21 02:50 UTC, TheNorthEestern commented on web_backend/filingapi/models.py
> +    titleOfClass = db.Column(db.String)
```suggestion
    name_of_issuer = db.Column(db.String)
    title_of_class = db.Column(db.String)
```

2021-04-21 02:51 UTC, TheNorthEestern commented on web_backend/filingapi/models.py
> +    votingAuthority_None = db.Column(db.Integer)
```suggestion
    ssh_prnamt = db.Column(db.Integer)
    ssh_prnamt_type = db.Column(db.String)
    put_call = db.Column(db.String)
    investment_discretion = db.Column(db.String)
    other_manager = db.Column(db.String)
    voting_authority_Sole = db.Column(db.Integer)
    voting_authority_Shared = db.Column(db.Integer)
    voting_authority_None = db.Column(db.Integer)
```

2021-04-21 04:46 UTC, datdo commented on web_backend/filingapi/models.py
> +    infotable_rows: Infotable
should this be a collection of Infotable objects?

2021-04-21 04:49 UTC, datdo requested changes

2021-04-21 04:49 UTC, datdo commented on web_backend/filingapi/models.py
> +        return "<User(accession_no='%s', cik_no='%s', nameOfIssuer='%s', " \
change user to Infotable

2021-04-21 04:49 UTC, datdo commented on web_backend/filingapi/models.py
> +        return "<User(accession_no='%s', cik_no='%s', filing_date='%s', company_name='%s')>" % (
change User to PrimaryDoc

2021-05-02 22:50 UTC, datdo approved these changes

2021-05-02 23:48 UTC, closed without merging