Feature/edgarfiling api
eharley19/filing13F_searcher pull request #50
Opened 2021-05-05 03:49 UTC by eharley19

2021-05-05 14:53 UTC, datdo requested changes

2021-05-05 14:53 UTC, datdo commented on python/edgar_filing_searcher/models.py
> +    filing_date: db.Date
db.Date vs datetime.date

2021-05-05 14:53 UTC, datdo commented on python/edgar_filing_searcher/api/routes/edgarfiling.py
> +    start_date = request.args.get('start_date')
these should be optional. So you should check to see if they exist first, and then apply the filter if they do.

2021-05-06 02:09 UTC, TheNorthEestern commented on python/edgar_filing_searcher/api/routes/company.py
> +            EdgarFiling.filing_date >= datetime.strptime(start_date, date_format))
```suggestion
        filings = filings.filter(
            EdgarFiling.filing_date >= datetime.strptime(start_date, date_format)
        )
```

2021-05-06 02:10 UTC, TheNorthEestern commented on python/edgar_filing_searcher/api/routes/company.py
> +            EdgarFiling.filing_date <= datetime.strptime(end_date, date_format))
```suggestion
        filings = filings.filter(
            EdgarFiling.filing_date <= datetime.strptime(end_date, date_format)
        )
```

2021-05-06 02:49 UTC, TheNorthEestern approved these changes

2021-05-06 03:03 UTC, datdo approved these changes

2021-05-06 03:04 UTC, merged