Fix 'object of type decimal is not json serializable' bug and added e…
eharley19/filing13F_searcher pull request #98
Opened 2021-09-07 21:58 UTC by rosealti

…ndpoints for company and data13f.

2021-09-09 00:16 UTC, datdo requested changes

2021-09-09 00:16 UTC, datdo commented on python/edgar_filing_searcher/api/routes/company.py
> +    """Route for results for search by company id and date"""
filings by company id and date

2021-09-09 00:16 UTC, datdo commented on python/edgar_filing_searcher/api/routes/company.py
> +    """Route for results for search by company id"""
company by company id

2021-09-09 00:16 UTC, datdo commented on python/edgar_filing_searcher/api/routes/company.py
> +    filings = EdgarFiling.query.filter(EdgarFiling.cik_no.like(f"{company_id}%"))
cik_no should equal company id

2021-09-09 00:16 UTC, datdo commented on python/edgar_filing_searcher/api/routes/company.py
> +@company_blueprint.route('/company/<company_id>/<accession_id>')
/company/<company_id>/filing/<filing_id>

2021-09-09 00:16 UTC, datdo commented on python/edgar_filing_searcher/api/routes/company.py
> +    """Route for results for search by accession no"""
doc string again.

2021-09-09 00:16 UTC, datdo commented on python/edgar_filing_searcher/api/routes/company.py
> +        filter(Data13f.cik_no == company_id, Data13f.accession_no.like(f"{accession_id}%"))
equals instead of like

2021-09-11 21:12 UTC, rosealti commented on python/edgar_filing_searcher/api/routes/company.py
> +    """Route for results for search by company id and date"""
Changed

2021-09-11 21:12 UTC, rosealti commented on python/edgar_filing_searcher/api/routes/company.py
> +    """Route for results for search by company id"""
Changed

2021-09-11 21:12 UTC, rosealti commented on python/edgar_filing_searcher/api/routes/company.py
> +    filings = EdgarFiling.query.filter(EdgarFiling.cik_no.like(f"{company_id}%"))
Changed

2021-09-11 21:12 UTC, rosealti commented on python/edgar_filing_searcher/api/routes/company.py
> +    """Route for results for search by accession no"""
Changed

2021-09-11 21:12 UTC, rosealti commented on python/edgar_filing_searcher/api/routes/company.py
> +        filter(Data13f.cik_no == company_id, Data13f.accession_no.like(f"{accession_id}%"))
Changed

2021-09-15 06:52 UTC, datdo requested changes

2021-09-15 06:52 UTC, datdo commented on python/edgar_filing_searcher/api/routes/routes.py
> +    """Route for search results by company name"""
search for companies by company name

2021-09-15 06:52 UTC, datdo commented on python/edgar_filing_searcher/api/routes/routes.py
> +        abort(400, description="Bad Requests")
Bad Request

2021-09-15 06:52 UTC, datdo commented on python/edgar_filing_searcher/api/routes/routes.py
> +    """Route for search results of filings by company id and date"""
Route for filings for the specified company, optionally filtered by date

2021-09-15 06:52 UTC, datdo commented on python/edgar_filing_searcher/api/routes/routes.py
> +    """Route for search results of filing by filing id"""
Route for data for specified edgar filing.

2021-09-15 06:52 UTC, datdo commented on python/tests/api/routes/test_routes.py
> +def test_get_filings_with_date_responseCode(client):  # add date param
add test for date behavior

2021-09-16 01:38 UTC, datdo approved these changes

2021-09-16 01:38 UTC, TheNorthEestern approved these changes

2021-09-16 01:39 UTC, merged